Read JSON from file when key:=file
skanehira/gjo pull request #6
Opened 2019-09-05 16:02 UTC by mattn

2019-09-05 16:03 UTC, mattn commented
You've better to add .travis.yml

2019-09-08 12:25 UTC, skanehira requested changes

2019-09-08 12:25 UTC, skanehira commented on main.go
> +			jsons[key] = parseValue(value)
変数を使う必要がないので、`jsons[kv[0]] = parseValue(kv[1])` にして頂けますか?

2019-09-08 12:25 UTC, skanehira commented on main_test.go
> +	}()
この追加分の意図が理解できなかったので、教えて頂けますか？

2019-09-08 12:54 UTC, mattn commented on main.go
> +			jsons[key] = parseValue(value)
done

2019-09-08 12:56 UTC, mattn commented on main_test.go
> +	}()
この対応を入れる前のテストを実行すると分かりますが、テスト結果として欲しくない情報が出力されています。テストの間だけこれを差し替えて綺麗なテスト結果にしています。

2019-09-08 14:12 UTC, skanehira commented on main_test.go
> +	}()
あー、結果を標準出力を出さないようにって意図なんですね
了解しました

2019-09-08 14:12 UTC, merged